[package]
name = "runbox-emulator"
version = "0.1.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
bash-emulator = { path = "../bash-emulator" }
emulator-core = { path = "../emulator-core" }
cmd-emulator = { path = "../cmd-emulator" }
powershell-emulator = { path = "../powershell-emulator" }
regex.workspace = true
serde.workspace = true
thiserror.workspace = true
windows-script-emulator = { path = "../windows-script-emulator" }
zip.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap.workspace = true
rustyline.workspace = true

[lints]
workspace = true
