[package]
name = "binary-inspector"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
goblin.workspace = true
hex.workspace = true
serde.workspace = true
sha1.workspace = true
sha2.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
authenticode = { version = "0.6.0", default-features = false, features = ["std"] }
cryptographic-message-syntax = { version = "0.27.0", default-features = false }

[lints]
workspace = true
